# Generated by Django 3.2.13 on 2022-05-18 23:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=512, verbose_name='Type')),
                ('state', models.CharField(choices=[('INIT', 'Init'), ('ACCEPTED', 'Accepted'), ('NO_AVAILABLE_WORKERS', 'No available workers'), ('ERROR', 'Error'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='INIT', max_length=24)),
                ('error', models.CharField(max_length=512, verbose_name='Error')),
                ('errors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=512), size=256, verbose_name='Errors')),
                ('result', models.CharField(max_length=512, verbose_name='Result')),
                ('transaction_id', models.CharField(max_length=512, verbose_name='Transaction id')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
