# Generated by Django 3.2.13 on 2022-05-18 23:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='errors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=512), default=[], size=256, verbose_name='Errors'),
        ),
    ]
