# Generated by Django 3.2.13 on 2022-05-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_wallet', '0002_alter_job_errors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_data', models.JSONField(default={})),
                ('response_data', models.JSONField(default={})),
                ('type', models.SmallIntegerField(choices=[(0, 'Undefined'), (1, 'Request'), (2, 'Job is created'), (3, 'Job status is updated'), (4, 'Account is created'), (5, 'Request to get all accounts info'), (6, 'Request to get account info')])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
    ]
